#!/bin/bash

# --- template --- {{{
readonly cf="\\033[0m"
readonly red="\\033[0;31m"
readonly green="\\033[0;32m"
readonly yellow="\\033[0;33m"

err() {
  local _date
  _date=$(showdate)
  echo -e "[$_date][${red}ERROR${cf}]: $1" 1>&2
}

warn() {
  local _date
  _date=$(showdate)
  echo -e "[$_date][${yellow}WARNING${cf}]: $1"
}

info() {
  local _date
  _date=$(showdate)
  echo -e "[$_date][INFO]: $1 "
}

succ() {
  local _date
  _date=$(showdate)
  echo -e "[$_date][${green}SUCCESS${cf}]: $1"
}

showdate() {
  local _date
  _date=$(date +%d-%H.%M)
  echo "$_date"
}

cleanup() {
  info "cleanup.."
}
#}}}

show_help() {
  cat <<'EOF'

USAGE:
  runeflex [options] <border_char>

OPTIONS:
  -h: help
  -t: test: runeflex_test
  -p: padding size
  -x: horizontal padding size
  -y: vertical padding size
  -b: border option

EXAMPLE:
EOF
}

run_runeflex() {
  local max_line_width=0
  local max_line_height=0
  local border_indexes=()
  local line=""
  local lines=()
  local file_inputs=()
  local file_input=""

  local file=""
  local height=0
  for file in "$@"; do
    file_input="$(replace_exception_string "$(cat "$file")")"
    file_inputs+=("$file_input")
    height="$(wc -l <<<"$file_input")"
    if [[ "$height" -gt "$max_line_height" ]]; then
      max_line_height="$height"
    fi
  done

  local i=0
  for file_input in "${file_inputs[@]}"; do
    if is_exists_file "$file"; then
      max_line_width="$(get_max_line_width "$file_input")"
      border_index=$((max_line_width + border_index + PADDING_X * 2 + 1))
      border_indexes+=("$border_index")

      local j=0
      local empty_count=0
      while read -r line; do
        if [[ -z ${lines[j]} ]]; then
          lines[j]="$(repeat_string "$MARGIN_CHAR" "$MARGIN_X")"
        fi
        empty_count="$((max_line_width - $(runewidth "$line")))"
        if [[ "$BORDER_CHAR_RUNEWIDTH" -eq 0 ]]; then
          if [[ "${#}" -eq $((i + 1)) ]]; then
            lines[j]="$BORDER_CHAR${lines[j]}$line$BORDER_CHAR"
          else
            if [[ -z "$line" ]]; then
              line="$(repeat_string "$EMPTY_CHAR" "$max_line_width")"
            fi
            lines[j]="$BORDER_CHAR${lines[j]}$line$(repeat_string "$EMPTY_CHAR" "$empty_count")$BORDER_CHAR$(repeat_string "$GAP_CHAR" "$GAP")"
          fi
        else
          if [[ $i -eq 0 ]]; then
            lines[j]="${lines[j]}$BORDER_CHAR$(repeat_string "$PADDING_CHAR" "$PADDING_X")$line$(repeat_string "$EMPTY_CHAR" "$empty_count")$(repeat_string "$PADDING_CHAR" "$PADDING_X")$BORDER_CHAR"
          else
            lines[j]="${lines[j]}$(repeat_string "$PADDING_CHAR" "$PADDING_X")$line$(repeat_string "$EMPTY_CHAR" "$empty_count")$(repeat_string "$PADDING_CHAR" "$PADDING_X")$BORDER_CHAR"
          fi
        fi
        ((j++))
      done <<<"$file_input"

      local k
      for ((k = 0; k < $((max_line_height - j)); k++)); do
        if [[ -z ${lines[j]} ]]; then
          lines[j]="$(repeat_string "$MARGIN_CHAR" "$MARGIN_X")"
        fi
        local index
        index="$((j + k))"
        if [[ "$BORDER_CHAR_RUNEWIDTH" -eq 0 ]]; then
          lines[index]="${lines[$index]}$(repeat_string "$GAP_CHAR" "$GAP")$(repeat_string "$EMPTY_CHAR" "$max_line_width")"
        else
          if [[ $i -eq 0 ]]; then
            lines[j]="${lines[j]}$BORDER_CHAR$(repeat_string "$PADDING_CHAR" "$PADDING_X")$(repeat_string "$EMPTY_CHAR" "$max_line_width")$(repeat_string "$PADDING_CHAR" "$PADDING_X")$BORDER_CHAR"
          else
            lines[j]="${lines[j]}$(repeat_string "$PADDING_CHAR" "$PADDING_X")$(repeat_string "$EMPTY_CHAR" "$max_line_width")$(repeat_string "$PADDING_CHAR" "$PADDING_X")$BORDER_CHAR"
          fi
        fi
      done
    else
      err_exit "$file file is not found" "$ERR_CODE_NOT_FOUND_INPUT_FILE"
    fi
    ((i++))
  done

  local max
  max="$(get_max_line_width "${lines[@]}")"
  local frame_empty_count="$((max - $((BORDER_CHAR_RUNEWIDTH * 2))))"
  local frame_line

  if [[ "$BORDER_CHAR_RUNEWIDTH" -ne 0 ]]; then
    frame_line="$(border_frame_line "$frame_empty_count" "${border_indexes[@]}")"
  fi

  if [[ "$BORDER_CHAR_RUNEWIDTH" -eq 0 ]]; then
    for ((i = 0; i < "$MARGIN_Y"; i++)); do
      new_line
    done
  else
    repeat_string "$BORDER_CHAR" "$max"
    new_line
    for ((i = 0; i < "$PADDING_Y"; i++)); do
      printf "%s" "$frame_line"
      new_line
    done
  fi

  for line in "${lines[@]}"; do
    printf "%s\n" "$line"
  done

  if [[ "$BORDER_CHAR_RUNEWIDTH" -ne 0 ]]; then
    for ((i = 0; i < "$PADDING_Y"; i++)); do
      printf "%s" "$frame_line"
      new_line
    done
    repeat_string "$BORDER_CHAR" "$max"
  fi
}

get_max_line_width() {
  local max
  local lines
  local l
  while read -r l; do
    if [[ $(runewidth "$l") -gt $max ]]; then
      max=$(runewidth "$l")
    fi
    lines+=("$l")
  done <<<"$1"
  printf "%d" "$max"
}

repeat_string() {
  local i
  if [[ 0 -ne $2 ]]; then
    for ((i = 1; i <= $2; i++)); do
      printf "%s" "$1"
    done
  fi
}

is_array_contains() {
  local i
  local j
  for i in "$@"; do
    if [[ $j -ne 0 ]]; then
      if [[ "$1" == "$i" ]]; then
        return 0
      fi
    fi
    ((j++))
  done
  return 1
}

replace_exception_string() {
  # shellcheck disable=SC2001
  printf "%s" "$1" | sed -e 's/0x0B/    /g' | # Vertical TAB
    sed -e 's/\t/    /g' |                    # TAB
    sed -e 's/\x08/  /g' |                    # backspace
    sed -e 's/\x09/  /g' |                    # Horizon TAB
    sed -e 's/\r/  /g' |                      # cr
    sed -e 's/\x0c/  /g' |                    # form feed
    sed -e 's/\0x7f/  /g' |                   # delete
    sed -e 's/\x1b/  /g'                      # escape
}

empty_block() {
  printf "%s" "$EMPTY_CHAR"
}

front_padding_block() {
  printf "%s" "$1"
  repeat_string "$GAP_CHAR" "$2"
}

back_padding_block() {
  repeat_string "$GAP_CHAR" "$2"
  printf "%s" "$1"
}

border_line() {
  repeat_string "$1" "$2"
}

new_line() {
  printf "\n"
}

border_frame_line() {
  local j
  printf "%s" "$BORDER_CHAR"
  for ((j = 0; j < "$1"; j++)); do
    if is_array_contains "$((j + 1))" "${@:2}"; then
      printf "%s" "$BORDER_CHAR"
    else
      printf "%s" "$EMPTY_CHAR"
    fi
  done
  printf "%s" "$BORDER_CHAR"
}

is_pipe() {
  if [ -p /dev/stdin ]; then
    return 0
  elif [ -p /dev/stdout ]; then
    return 0
  else
    return 1
  fi
}

is_exists() {
  which "$1" >/dev/null 2>&1
  return $?
}

is_exists_file() {
  if [[ -e "$1" ]]; then
    return 0
  else
    return 1
  fi
}

is_number() {
  if [[ "$1" =~ ^[0-9]+$ ]]; then
    return 0
  else
    return 1
  fi
}

err_exit() {
  err "$1"
  if [[ -z "$2" ]]; then
    exit 1
  else
    exit "$2"
  fi
}

exit_health() {
  if [[ -n "$1" ]]; then
    info "$1"
  fi
  exit 0
}

exit_quit() {
  err "quit" 1>&2
  exit 1
}

# locale
export LC_ALL=C

# IFS
IFS=""

# trap
trap exit_quit QUIT SIGINT

# vars
PADDING_X=1
PADDING_Y=1
PADDING_CHAR=" "
MARGIN_X=0
MARGIN_Y=0
MARGIN_CHAR=" "
BORDER_CHAR=""
GAP_CHAR=" "
GAP=1
EMPTY_CHAR=" "
BORDER_CHAR_RUNEWIDTH=0
TEST_FILE="./runeflex_test"
POSITIONAL_ARGS=()

## error code
ERR_CODE_INVALID_OPTION=3
ERR_CODE_INVALID_BORDER_CHAR_WIDTH=4
ERR_CODE_NOT_FOUND_RUNEWIDTH=5
ERR_CODE_NOT_FOUND_INPUT_FILE=6
ERR_CODE_NOT_FOUND_TESTFILE=7

while [[ $# -gt 0 ]]; do
  case $1 in
  -h | --help)
    show_help
    exit_health ""
    ;;
  -t | --test)
    if [ -f "$TEST_FILE" ]; then
      info "start testing"
      # shellcheck disable=SC1090
      . "$TEST_FILE"
      info "end testing"
    else
      err_exit "$TEST_FILE file is not found" "$ERR_CODE_NOT_FOUND_TESTFILE"
    fi
    exit_health ""
    shift # past argument
    shift # past value
    ;;
  -g | --gap)
    if is_number "$2"; then
      GAP="$2"
    else
      err_exit "--gap option argument is expected the number" "$ERR_CODE_INVALID_OPTION"
    fi
    shift # past argument
    shift # past value
    ;;
  -p | --padding)
    if is_number "$2"; then
      PADDING_X="$2"
      PADDING_Y="$2"
    else
      err_exit "--padding option argument is expected the number" "$ERR_CODE_INVALID_OPTION"
    fi
    shift # past argument
    shift # past value
    ;;
  -px | --padding-x)
    if is_number "$2"; then
      PADDING_X="$2"
    else
      err_exit "--padding-x option argument is expected the number" "$ERR_CODE_INVALID_OPTION"
    fi
    shift # past argument
    shift # past value
    ;;
  -py | --padding-y)
    if is_number "$2"; then
      PADDING_Y="$2"
    else
      err_exit "--padding-y option argument is expected the number" "$ERR_CODE_INVALID_OPTION"
    fi
    shift # past argument
    shift # past value
    ;;
  -m | --margin)
    if is_number "$2"; then
      MARGIN_X="$2"
      MARGIN_Y="$2"
    else
      err_exit "--margin option argument is expected the number" "$ERR_CODE_INVALID_OPTION"
    fi
    shift # past argument
    shift # past value
    ;;
  -mx | --margin-x)
    if is_number "$2"; then
      MARGIN_X="$2"
    else
      err_exit "--margin-x option argument is expected the number" "$ERR_CODE_INVALID_OPTION"
    fi
    shift # past argument
    shift # past value
    ;;
  -my | --margin-y)
    if is_number "$2"; then
      MARGIN_Y="$2"
    else
      err_exit "--margin-y option argument is expected the number" "$ERR_CODE_INVALID_OPTION"
    fi
    shift # past argument
    shift # past value
    ;;
  -b | --border)
    if [[ -$(runewidth "$2") -lt 3 ]]; then
      BORDER_CHAR="$2"
    else
      err_exit "--border option argument is expected the number" "$ERR_CODE_INVALID_OPTION"
    fi
    shift
    shift
    ;;
  -* | --*)
    err_exit "Invalid option" "$ERR_CODE_INVALID_OPTION"
    break
    ;;
  *)
    POSITIONAL_ARGS+=("$1") # save positional arg
    shift                   # past argument
    ;;
  esac
done

# restore positional parameters
set -- "${POSITIONAL_ARGS[@]}"

# fix box char runewidth
BORDER_CHAR_RUNEWIDTH="$(runewidth "$BORDER_CHAR")"

# validation
if [[ -z "$BORDER_CHAR_RUNEWIDTH" || "$BORDER_CHAR_RUNEWIDTH" -gt 2 ]]; then
  err_exit "String is over 2 runewidth" "$ERR_CODE_INVALID_BORDER_CHAR_WIDTH"
elif ! is_exists "runewidth"; then
  err_exit "Command not found: runewidth" "$ERR_CODE_NOT_FOUND_RUNEWIDTH"
else
  out="$(run_runeflex "$@")"
  printf "%s\n" "$out"
  ## How to save bottom empty line in variable ?
  if [[ "$BORDER_CHAR_RUNEWIDTH" -eq 0 ]]; then
    for ((i = 0; i < "$MARGIN_Y"; i++)); do
      new_line
    done
  fi
fi
